#!/bin/bash

set -e

. /usr/local/google/home/michaelbausor/dev/veneer/regeneration-php-local/set-env.sh

API_ARTMAN_YAML="google/bigtable/artman_bigtable.yaml"
API_ARTMAN_OUTPUT_DIR="google-cloud-bigtable-v2"
API_GCP_FOLDER_NAME="Bigtable"

. $REGEN_DIR/regenerate-single.sh

source ./dev/sh/gapic-generation-functions.sh
setup_environment
regenerate_container_v1
post_regenerate
