#!/bin/bash

set -e

. /usr/local/google/home/michaelbausor/dev/veneer/regeneration-php-local/set-env.sh

API_ARTMAN_YAML="google/bigtable/admin/artman_bigtableadmin.yaml"
API_ARTMAN_OUTPUT_DIR="google-cloud-bigtable-admin-v2"
API_GCP_FOLDER_NAME="Bigtable"
GOOGLE_CLOUD_PHP_SRC="src/Admin"
GOOGLE_CLOUD_PHP_TEST="src/Admin"

. $REGEN_DIR/regenerate-single.sh

source ./dev/sh/gapic-generation-functions.sh
setup_environment
regenerate_container_v1
post_regenerate
