#!/bin/bash

set -e

. /usr/local/google/home/michaelbausor/dev/veneer/regeneration-php-local/set-env.sh

API_ARTMAN_YAML="google/devtools/clouderrorreporting/artman_errorreporting.yaml"
API_ARTMAN_OUTPUT_DIR="google-cloud-error-reporting-v1beta1"
API_GCP_FOLDER_NAME="ErrorReporting"

. $REGEN_DIR/regenerate-single.sh

source ./dev/sh/gapic-generation-functions.sh
setup_environment
regenerate_container_v1
post_regenerate
