#!/bin/bash

set -e

. /usr/local/google/home/michaelbausor/dev/veneer/regeneration-php-local/set-env.sh

API_ARTMAN_YAML="google/logging/artman_logging.yaml"
API_ARTMAN_OUTPUT_DIR="google-cloud-logging-v2"
API_GCP_FOLDER_NAME="Logging"

. $REGEN_DIR/regenerate-single.sh

source ./dev/sh/gapic-generation-functions.sh
setup_environment
regenerate_container_v1
post_regenerate
