#!/bin/bash

set -e

. /usr/local/google/home/michaelbausor/dev/veneer/regeneration-php-local/set-env.sh

API_ARTMAN_YAML="google/cloud/oslogin/artman_oslogin_v1beta.yaml"
API_ARTMAN_OUTPUT_DIR="google-cloud-os-login-v1beta"
API_GCP_FOLDER_NAME="OsLogin"

. $REGEN_DIR/regenerate-single.sh

source ./dev/sh/gapic-generation-functions.sh
setup_environment
regenerate_container_v1
post_regenerate
