#!/bin/bash

set -e

. /usr/local/google/home/michaelbausor/dev/veneer/regeneration-php-local/set-env.sh

API_ARTMAN_YAML="google/cloud/redis/artman_redis_v1beta1.yaml"
API_ARTMAN_OUTPUT_DIR="google-cloud-redis-v1beta1"
API_GCP_FOLDER_NAME="Redis"

. $REGEN_DIR/regenerate-single.sh

source ./dev/sh/gapic-generation-functions.sh
setup_environment
regenerate_container_v1
post_regenerate
